services:
  db:
    image: mariadb:latest
    platform: linux/amd64
    volumes:
      - sixt_wordpress_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    platform: linux/amd64
    expose:
      - "80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://sixt.test');
        define('WP_SITEURL', 'https://sixt.test');
        define('FORCE_SSL_ADMIN', true);
        if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
            $_SERVER['HTTPS'] = 'on';
            define('FORCE_SSL', true);
        }
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
    # Install WP-CLI in the container
    entrypoint: >
      /bin/sh -c '
      if [ ! -f /usr/local/bin/wp ]; then
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar &&
        chmod +x wp-cli.phar &&
        mv wp-cli.phar /usr/local/bin/wp;
      fi &&
      docker-entrypoint.sh apache2-foreground'

  nginx-proxy:
    image: nginx:alpine
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../shared/certs:/etc/nginx/certs:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - wordpress

volumes:
  sixt_wordpress_db_data: {}
